remote_theme: "mmistakes/minimal-mistakes@4.14.1"
plugins:
  - jekyll-include-cache

title: "PMM2 Foldable Docs Demo"
search: true
search_full_content: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "docs"
